version: '3.7'

services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db
    environment:
      - HAPI_FHIR_VALIDATION_REQUESTS_ENABLED=false # setting to enable/disable structure definition validation against incoming data. See https://medblocks.com/blog/how-to-enable-fhir-profile-validation-with-hapi-fhir-jpa-server


  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi

configs:
  hapi:
     file: ./hapi.application.yaml